CREATE TABLE SUPPLIER (
    SUPPLIER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    WEBSITE VARCHAR(255),
    LOCATION VARCHAR(255) NOT NULL,
    NATURE_OF_BUSINESS VARCHAR(50) NOT NULL
);

CREATE TABLE SUPPLIER_PROCESSES (
    SUPPLIER_ID BIGINT NOT NULL,
    PROCESS VARCHAR(50) NOT NULL,
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
);
